### ISSUE TITLE
Were you able to reproduce speech?

### ISSUE THREAD

**Issue by malyasova** [DongyaoZhu/VQ-VAE-WaveNet#3]
Hello, DongyaoZhu! Were you able to reproduce speech with your model? I've tried running 
python generate.py -restore=saved_vqvae/weights-11061 -save=generated -speakers=p225 -audio=data/VCTK-Corpus/wav48/p225/p225_001.wav
and it outputs noise.

**Comment by DongyaoZhu** [comment]
Hi malyasova,

Its unlikely to have any good results with only 11061 steps.
I trained for 100k steps, and still reconstructed with much noise. I am still tuning.
You could also try deleting the VQ part and train it as a normal AutoEncoder, which you will have clear speech reconstructed, but it will just ignore speaker id, i.e. no speaker conversion possible.

**Comment by Dirvann** [comment]
Hi @DongyaoZhu, 
How would I set the parameters to train without caring about the speaker ID to be able to speed up the process to get clear speech? 

would it be enough to remove the 'speaker' from the model arguments of the VQVAE class in the train.py arguments given?
https://github.com/DongyaoZhu/VQ-VAE-WaveNet/blob/a429cde6b50f3af2ee233448178919e5b2b7614d/train.py#L62-L73

And then afterwards in the generate.py also remove the speaker parameter?
https://github.com/DongyaoZhu/VQ-VAE-WaveNet/blob/a429cde6b50f3af2ee233448178919e5b2b7614d/generate.py#L71-L82

As in the VQVAE class it doesn't set the num_speakers or speaker_embedding settings.
https://github.com/DongyaoZhu/VQ-VAE-WaveNet/blob/a429cde6b50f3af2ee233448178919e5b2b7614d/model.py#L9-L23

---------------------------------

Also does the VQ part only affect the encoding? Because I want to implement using another parametric encoder. Would disabling or enabling VQ have any effect on that?

**Comment by DongyaoZhu** [comment]
Hi, could you move this topic to a new open issue?
